# ==== CONFIGURE =====
# Use a Node 19 base image
FROM node:19-alpine 
# Set the working directory to /app inside the container
WORKDIR /med_clinic_frontend
# Copy package.json and package-lock.json to the working directory
COPY /package*.json /med_clinic_frontend 
# Install dependencies
RUN npm install
# Copy all other app files
COPY . /med_clinic_frontend
# ==== RUN =======
# Expose the port on which the app will be running (3000 is the default that `serve` uses)
EXPOSE 3000
# Start the app
CMD [ "npm", "start"]